### ISSUE TITLE
issue with path validation

### ISSUE THREAD

**Issue by AVVS** [delvedor/find-my-way#32]
#30 causes this:

With this PR in place I get the following error:

```
  1) Server#player "before all" hook: start webserver:

      Uncaught AssertionError [ERR_ASSERTION]: The path could not be empty
      + expected - actual

      -false
      +true
      
      at Router.on (node_modules/find-my-way/index.js:53:3)
      at Router.on (node_modules/find-my-way/index.js:43:12)
      at Router.all (node_modules/find-my-way/index.js:360:8)
      at Function._setNotFoundHandler (node_modules/fastify/fastify.js:602:18)
      at after (node_modules/fastify/fastify.js:559:27)
      at Function._encapsulateThreeParam (node_modules/avvio/boot.js:268:7)
      at Boot.callWithCbOrNextTick (node_modules/avvio/boot.js:223:5)
      at Boot._after (node_modules/avvio/boot.js:180:26)
```

Likely fails here: https://github.com/fastify/fastify/blob/master/fastify.js#L594-L598

Specifically for these instructions so as not to poke around repos:

```
      var prefix = this._RoutePrefix.prefix
      var star = '/*'

      fourOhFour.all(prefix + star, startHooks, store)  // <-- this seem to be failing
      fourOhFour.all(prefix || '/', startHooks, store)
```

Where prefix is `''` - i haven't yet added a test-case to verify this, and why it happens, and maybe it simply should be `*` instead of `/*` in the fastify, but well, still a comment here!

**Comment by delvedor** [comment]
Closing for inactivity :)
Related: https://github.com/fastify/fastify/issues/324
